# Compose fileのバージョン指定
version: "3.7"

# コンテンツ
services:
# ---------------------------------------------------
#  code-server
# ---------------------------------------------------
  code-server:
    container_name: "code-server"
#    image: tamatan/code-server:v202205131545-g1.18.2-p3.10.4-n18.1.0-java-cpp
    build:
      context: .
    volumes:
      - ./data/code-server/app:/works/app
    ports:
      - "8080:8080"
    environment:
      PASSWORD: "password"  # パスワード設定
